---
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: ./cmd/codedeploy-trigger
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version -}}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^Bump'
release:
  draft: true
