---
name: go-licenses
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: "${{ github.workflow }}-$${{ github.pull_request.number || github.run_id }}"
  cancel-in-progress: true
jobs:
  go-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true
      - run: go install github.com/google/go-licenses@v1.6.0
      - run: go-licenses check --include_tests --disallowed_types=restricted,forbidden,unknown ./...
